version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  test:
    docker:
      - image: circleci/ruby:2.3.3-node
        environment:
          POSTGRES_USER: postgres
          RAILS_ENV: test
          TEST_DB: circle_test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
    executor: ruby/default
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install phantomjs
      - run: bundle -v
      - ruby/bundle-install
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      - run: bundle exec rspec

workflows:
  version: 2
  workflow:
    jobs:
    - test
