version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          RAILS_ENV: development
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle -v
      - ruby/bundle-install
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          POSTGRES_USER: postgres
          RAILS_ENV: test
          TEST_DB: circle_test
          PHANTOM_JS: phantomjs-2.1.1-linux-x86_64
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
        environment:
          cluster.name: transbucket-test
          xpack.security.enabled: false
          transport.host: localhost
          network.host: 127.0.0.1
          http.port: 9200
          discovery.type: single-node
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: sudo apt-get update
      - run: sudo apt-get install libfontconfig1
      - run: wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
      - run: tar -xjf $PHANTOM_JS.tar.bz2
      - run: sudo mv $PHANTOM_JS /usr/local/share
      - run: sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
      - run: bundle -v
      - ruby/bundle-install
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for elasticsearch
          command: dockerize -wait tcp://localhost:9200 -timeout 1m
      - run:
          name: Lift elasticsearch disk watermark restrictions
          command: |
            curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_cluster/settings -d '{ "transient": { "cluster.routing.allocation.disk.threshold_enabled": false } }'
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      - run: bundle exec rspec || bundle exec rspec --only-failures || bundle exec rspec --only-failures

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
