version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  test:
    docker:
      - image: circleci/ruby:2.3.8-stretch-node-browsers
        environment:
          POSTGRES_USER: postgres
          RAILS_ENV: test
          TEST_DB: circle_test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
        environment:
          cluster.name: transbucket-test
          xpack.security.enabled: false
          transport.host: localhost
          network.host: 127.0.0.1
          http.port: 9200
          discovery.type: single-node
    executor: ruby/default
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install phantomjs
      - run: bundle -v
      - ruby/bundle-install
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for elasticsearch
          command: dockerize -wait tcp://localhost:9200 -timeout 1m
      - run:
          name: Lift elasticsearch disk watermark restrictions
          command: |
            curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_cluster/settings -d '{ "transient": { "cluster.routing.allocation.disk.threshold_enabled": false } }'
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      - run: bundle exec rspec

workflows:
  version: 2
  workflow:
    jobs:
    - test
