defaults: &defaults
  adapter: postgresql
  prepared_statements: false
  host: <%= ENV['POSTGRES_HOST'] || "localhost" %>
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] || "Alex" %>
  password: <%= ENV['POSTGRES_PASSWORD'] || "" %>
  morphology: stem_en
  enable_star: true
  min_infix_len: 3

development:
  <<: *defaults
  database: psql_development

test:
  <<: *defaults
  database: <%= ENV['TEST_DB'] || ("psql_test" + (ENV['TEST_ENV_NUMBER'] || "")) %>

production:
  <<: *defaults
  database: psql_production
