development: &default
  transport_options:
    request:
      timeout: !!integer 1000
test:
  <<: *default
staging:
  transport_options:
    request:
      timeout: !!integer 900
production:
  transport_options:
    request:
      timeout: !!integer 600
